### ISSUE TITLE
Help for the dataset

### ISSUE THREAD

**Issue by hityzy1122** [JJanai/slowflow#1]
Thanks for the release of the code. However I can find the dataset of Slowflow-240fps and Sintel-1008fps on this website http://www.cvlibs.net/projects/slow_flow/. As the provided "Benchmark Dataset" and "Teaser Dataset" don't seem to be the Slowflow-240fps or Sintel-1008fps in this website.

looking forward to your replay
Thanks

**Comment by JJanai** [comment]
Thanks for your message.
The high-speed datasets are now available on the project webpage:
http://www.cvlibs.net/projects/slow_flow/

Best,
Joel

**Comment by hityzy1122** [comment]
> Thanks for your message.
> The high-speed datasets are now available on the project webpage:
> http://www.cvlibs.net/projects/slow_flow/
> 
> Best,
> Joel

Thanks!!!!!
